# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LabelTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=1000)),
                ('description_task', models.TextField(max_length=10000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_task', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Category')),
                ('executive_man', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('label_task', models.ManyToManyField(blank=True, default='', to='task.LabelTask')),
            ],
        ),
    ]
